name: Acceptance tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed

jobs:
  acceptance-tests:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - image_name: py
            test_user: jovyan
          - image_name: cuda-tf
            build_arg: BASE_IMAGE=py
            test_user: jovyan
          - image_name: generic
            build_arg: RENKU_BASE=py
            test_user: jovyan
          - image_name: julia
            build_arg: BASE_IMAGE=py
            test_user: jovyan
          - image_name: r
            build_arg: RENKU_BASE=py
            test_user: jovyan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          if ['${{ matrix.build_arg }}' == '']
          then
          docker build -t ${{ matrix.image_name }} docker/${{ matrix.image_name }}/
          else
          docker build -t ${{ matrix.image_name }} --build-arg ${{matrix.build_arg}} docker/${{ matrix.image_name }}/
          fi
      - name: Py Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: ${{ matrix.image_name }}
          TEST_USER_NAME: ${{ matrix.test_user }}
        with:
          working-directory: tests
          command: npx mocha test.js
  