name: Acceptance tests

on:
  pull_request:
    types:
    - synchronize

jobs: 
  acceptance-tests:
    strategy:
      matrix:
        include:
          - image_name: py
            test_user: jovyan
          - image_name: cuda-tf
            build_arg: BASE_IMAGE=localhost:5000/py
            test_user: jovyan
          - image_name: generic
            build_arg: RENKU_BASE=localhost:5000/py
            test_user: jovyan
          - image_name: julia
            build_arg: BASE_IMAGE=localhost:5000/py
            test_user: jovyan
          - image_name: r
            build_arg: RENKU_BASE=localhost:5000/py
            test_user: jovyan
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: actions/checkout@v2
      - name: Build Py Image
        uses: docker/build-push-action@v2
        with:
          context: docker/${{ matrix.image_name }}/
          push: true
          tags: localhost:5000/${{ matrix.image_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move Cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Build Test Image
        uses: docker/build-push-action@v2.6.1
        if: ${{ matrix.image_name != 'py' }}
        with:
          context: docker/${{ matrix.image_name }}/
          tags: localhost:5000/${{ matrix.image_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            RENKU_BASE=localhost:5000/py
            BASE_IMAGE=localhost:5000/py
          push: true
      - name: Move Cache
        if: ${{ matrix.image_name != 'py' }}
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: localhost:5000/${{ matrix.image_name }}
          TEST_USER_NAME: ${{ matrix.test_user }}
        with:
          working-directory: tests
          command: npx mocha test.js
  