name: Acceptance tests

on: ["push"]
  # pull_request:
  #   types:
  #   - opened
  #   - edited
  #   - synchronize
  #   - reopened
  #   - closed

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build all images
        run: |
          docker build -t py docker/py/
          docker build -t cuda-tf --build-arg BASE_IMAGE=py docker/cuda-tf/
          docker build -t generic --build-arg RENKU_BASE=py  docker/generic/
          docker build -t julia --build-arg BASE_IMAGE=py docker/julia/
          docker build -t r --build-arg RENKU_BASE=py docker/r/
      - uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: py
        with:
          working-directory: tests
          command: npx mocha test.js
      - uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: cuda-tf
        with:
          working-directory: tests
          command: npx mocha test.js
      - uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: generic
        with:
          working-directory: tests
          command: npx mocha test.js
      - uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: julia
        with:
          working-directory: tests
          command: npx mocha test.js
      - uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: r
        with:
          working-directory: tests
          command: npx mocha test.js
  