name: Acceptance tests

on:
  pull_request:
    types:
    - synchronize

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build all images
        run: |
          docker build -t py docker/py/
          docker build -t cuda-tf --build-arg BASE_IMAGE=py docker/cuda-tf/
          docker build -t generic --build-arg RENKU_BASE=py  docker/generic/
          docker build -t julia --build-arg BASE_IMAGE=py docker/julia/
          docker build -t r --build-arg RENKU_BASE=py docker/r/
      - name: Py Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: py
          TEST_USER_NAME: jovyan
        with:
          working-directory: tests
          command: npx mocha test.js
      - name: Cuda-tf Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: cuda-tf
          TEST_USER_NAME: jovyan
        with:
          working-directory: tests
          command: npx mocha test.js
      - name: Generic Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: generic
          TEST_USER_NAME: jovyan
        with:
          working-directory: tests
          command: npx mocha test.js
      - name: Julia Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: julia
          TEST_USER_NAME: jovyan
        with:
          working-directory: tests
          command: npx mocha test.js
      - name: R Image Acceptance Tests
        uses: cypress-io/github-action@v2
        env:
          TEST_IMAGE_NAME: r
          TEST_USER_NAME: rstudio
        with:
          working-directory: tests
          command: npx mocha test.js
