name: Renku Base Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        RENKU_VERSION: ["", "0.8.2", "0.9.0"]
        EXTENSIONS: ["base", "r", "r-bioconductor_3_10", "cuda-9.2", "cuda-10.0-tensorflow-1.14"]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Renku Docker pull request images for testing
      if: github.event_name == 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u="${{ secrets.DOCKER_USERNAME }}" --password-stdin ${DOCKER_REGISTRY}
        docker build docker/${{ matrix.EXTENSIONS }} --tag $RENKU_DOCKER_TAG
        docker push $RENKU_DOCKER_TAG
      env:
        GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
        RENKU_DOCKER_TAG: renku/singleuser-${{ matrix.EXTENSIONS }}:$GIT_HASH-renku${{ matrix.RENKU_VERSION }}

    # - uses: actions/checkout@v2
    # - name: Build the Renku Docker master tagged images
    #   #if: github.event_name == 'pull_request'
    #   run: |
    #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u="${{ secrets.DOCKER_USERNAME }}" --password-stdin ${DOCKER_REGISTRY}
    #     docker build docker/${{ matrix.EXTENSIONS }} --tag $RENKU_DOCKER_TAG
    #     docker push $RENKU_DOCKER_TAG
    #   env:
    #     GIT_TAG: $(echo ${GITHUB_REF} | cut -d'/' -f 3)
    #     RENKU_DOCKER_TAG: renku/singleuser-${{ matrix.EXTENSIONS }}:$GIT_TAG-renku${{ matrix.RENKU_VERSION }}
