name: Renku Base Docker Image CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        RENKU_VERSION: ["", "0.8.2", "0.9.0"]
        EXTENSIONS: ["base", "r", "r-bioconductor_3_10", "cuda-9.2", "cuda-10.0-tensorflow-1.14"]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Renku Base Docker image
      run: docker build docker/${{ matrix.EXTENSIONS }} --tag renku/singleuser-${{ matrix.EXTENSIONS }}:$(date +%s)-renku${{ matrix.RENKU_VERSION }}
      
